document.addEventListener('DOMContentLoaded', () => {

  const container = document.getElementById('prototype_3')
  const text = document.createElement('div')
  const frame = document.createElement('div')
  const button_1 = document.createElement('div')
  const button_2 = document.createElement('div')
  const button_3 = document.createElement('div')
  const button_4 = document.createElement('div')
  const button_5 = document.createElement('div')
  const button_6 = document.createElement('div')
  const button_7 = document.createElement('div')
  const button_8 = document.createElement('div')
  const button_9 = document.createElement('div')

  text.innerText = 'ЧБ-кнопульки'
  frame.classList.add('frame')
  button_1.classList.add('button')
  button_2.classList.add('button')
  button_3.classList.add('button')
  button_4.classList.add('button')
  button_5.classList.add('button_long')
  button_6.classList.add('button')
  button_7.classList.add('button_long')
  button_8.classList.add('button')
  button_9.classList.add('button_long')
  text.classList.add('text')

  container.appendChild(text)
  container.appendChild(frame)
  frame.appendChild(button_1)
  frame.appendChild(button_2)
  frame.appendChild(button_3)
  frame.appendChild(button_4)
  frame.appendChild(button_5)
  frame.appendChild(button_6)
  frame.appendChild(button_7)
  frame.appendChild(button_8)
  frame.appendChild(button_9)
})
